
services:
  db:
    image: postgres:15
    container_name: backtobackup-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  minio:
    image: minio/minio:latest
    container_name: backtobackup-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    image: node:22-alpine
    container_name: backtobackup-api
    restart: on-failure
    working_dir: /root/app/packages/api
    environment:
      DB_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your_jwt_refresh_secret}
      JWT_REGISTER_DEVICE_SECRET: ${JWT_REGISTER_DEVICE_SECRET:-your_jwt_register_device_secret}
      JWT_DEVICE_SECRET: ${JWT_DEVICE_SECRET:-your_jwt_device_secret}
      JWT_DEVICE_REFRESH_SECRET: ${JWT_DEVICE_REFRESH_SECRET:-your_jwt_device_refresh_secret}
    volumes:
      - ..:/root/app
      - api_node_modules:/root/app/packages/api/node_modules
    command: >
      sh -c "
        cd /root/app && npm install &&
        cd /root/app/packages/api &&
        npm run start:dev
      "
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio

  frontend:
    image: node:22-alpine
    container_name: backtobackup-frontend
    restart: on-failure
    working_dir: /root/app/packages/frontend
    environment:
      NODE_ENV: development
    volumes:
      - ../packages/frontend:/root/app/packages/frontend
      - frontend_node_modules:/root/app/packages/frontend/node_modules
    command: >
      sh -c "
        npm install &&
        npm run start
      "
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  api_node_modules:
  frontend_node_modules:

