
services:
  db:
    image: postgres:15
    container_name: backtobackup-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  minio:
    image: minio/minio:latest
    container_name: backtobackup-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    image: node:22-alpine
    container_name: backtobackup-api
    restart: on-failure
    environment:
      DB_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: ['/bin/sh', '-c', 'echo "This is a dev container, application is launched via exec command" && while :; do sleep 2073600; done']
    volumes:
      - ../:/root/app
    depends_on:
      - db
      - minio
    ports:
      - "3000:3000"
